spring.data.mongodb.uri=mongodb+srv://root:200135@springboot.kidmixi.mongodb.net/?retryWrites=true&w=majority&appName=SpringBoot
spring.data.mongodb.database=fitfusion

spring.jpa.hibernate.ddl-auto=update




